Bump arkime version to 4.2
naps-dev/testdrive pull request #9
Opened 2023-04-17 19:50 UTC by docandrew

2023-04-17 22:48 UTC, jamesallen-atx approved these changes

2023-04-19 14:47 UTC, mikevanhemert requested changes

2023-04-19 14:47 UTC, mikevanhemert commented on packages.yaml
> +  version: v4.2.0
Can you follow the versioning scheme and tag as v4.2.0-1? https://coda.io/d/Cyber_dJzHMU5kknC/VOLTRN-Capability-Versioning_suriD#_luO9Q

We can pivot but should follow the ADR process and change things for reasons

2023-04-19 21:38 UTC, mikevanhemert approved these changes

2023-04-21 16:03 UTC, jamesallen-atx approved these changes

2023-04-24 20:04 UTC, merged